server:
  port: 8790

spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

zuul:
  routes:
    welcome-service:
      path: /welcome/**
      serviveId: welcome-service
      stripPrefix: true
    random-service:
      path: /random/**
      serviveId: random-service
      stripPrefix: true

ribbon:
  readTimeout: 50000
  socketTimeout: 50000