server:
  port: 0

management:
  server:
    port: 0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: welcome-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  healthcheck:
    enabled: true
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2